
development:
  num_top_tags: 10
  cache_tags_time_hours: 1
  max_returned_map: 32
  iframe_domain: http://dev.placeling.com:3000
  # To test properly, set to iframe.placeling.com:3000 and update /etc/hosts to map localhost to that


test:
  num_top_tags: 10
  cache_tags_time_hours: 1
  max_returned_map: 32
  iframe_domain: http://test.placeling.com:3000

staging:
  num_top_tags: 10
  cache_tags_time_hours: 1
  max_returned_map: 32
  iframe_domain: http://staging.placeling.com

# set these environment variables on your prod server
production:
  num_top_tags: 10
  cache_tags_time_hours: 1
  max_returned_map: 32
  iframe_domain: https://iframe.placeling.com

