development:
  host: localhost
  database: chatham_development
  autocreate_indexes: true


test:
  host: localhost
  database: chatham_test
  autocreate_indexes: true

staging:
  host: localhost
  database: chatham_staging

# set these environment variables on your prod server
production:
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  #don't autocreate indexes in production, use the rake task rake db:mongoid:create_indexes instead
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
