development:
  host: localhost
  database: chatham_development
  #autocreate_indexes: true
  raise_not_found_error: false
  allow_dynamic_fields: false
  identity_map_enabled: true


test:
  host: localhost
  database: chatham_test
  autocreate_indexes: true
  raise_not_found_error: false
  allow_dynamic_fields: false
  identity_map_enabled: true

staging:
  host: ip-10-170-90-180.us-west-1.compute.internal
  database: chatham_staging
  raise_not_found_error: false
  identity_map_enabled: true
  pool_size: 2

# set these environment variables on your prod server
production:
  host: ip-10-124-222-125.ec2.internal
  database: chatham_production
  raise_not_found_error: false
  identity_map_enabled: true
  pool_size: 2
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
