development:
  host: localhost
  database: chatham_development
  autocreate_indexes: true
  raise_not_found_error: false
  allow_dynamic_fields: false


test:
  host: localhost
  database: chatham_test
  autocreate_indexes: true
  raise_not_found_error: false
  allow_dynamic_fields: false

staging:
  host: 10.170.90.180
  database: chatham_staging
  raise_not_found_error: false
  pool_size: 2

# set these environment variables on your prod server
production:
  host: 10.120.65.248
  database: chatham_production
  raise_not_found_error: false
  pool_size: 2
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
