development:
  host: localhost
  database: chatham_development
  autocreate_indexes: true
  raise_not_found_error: false
  allow_dynamic_fields: false


test:
  host: localhost
  database: chatham_test
  autocreate_indexes: true
  raise_not_found_error: false
  allow_dynamic_fields: false

staging:
  host: ec2-50-18-80-62.us-west-1.compute.amazonaws.com
  database: chatham_staging
  raise_not_found_error: false
  pool_size: 2

# set these environment variables on your prod server
production:
  host: ec2-107-22-193-101.compute-1.amazonaws.com
  database: chatham_production
  raise_not_found_error: false
  pool_size: 2
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
