development:
  db: 0
  host: localhost
  port: 6379
  namespace: chatham_dev
  redis: redis://localhost:6379/0/chatham_dev
test:
  db: 1
  host: localhost
  port: 6379
  namespace: chatham_test
  redis: redis://localhost:6379/1/chatham_test
staging:
  db: 0
  host: localhost
  port: 6379
  namespace: chatham_staging
  redis: redis://localhost:6379/0/chatham_staging
production:
  db: 0
  host: localhost
  port: 6379
  namespace: placeling_production
  redis: redis://localhost:6379/0/placeling_production
