development:
  db: 0
  host: localhost
  port: 6379
  namespace: placeling_dev
test:
  db: 1
  host: localhost
  port: 6379
  namespace: placeling_test
staging:
  db: 0
  host: ec2-184-72-38-73.us-west-1.compute.amazonaws.com
  port: 6379
  namespace: placeling_stag
production:
  db: 0
  host: ec2-107-22-193-101.compute-1.amazonaws.com:6379
  port: 6379
  namespace: placeling_prod
