development:
  db: 0
  host: localhost
  port: 6379
  namespace: placeling_dev
test:
  db: 1
  host: localhost
  port: 6379
  namespace: placeling_test
staging:
  db: 0
  host: localhost
  port: 6379
  namespace: placeling_staging
production:
  db: 0
  host: ip-10-124-222-125.ec2.internal
  port: 6379
  namespace: placeling_production
