generate_sitemap:
  cron: "0 */4 * * *"
  class: RegenerateSiteMap
  queue: high
  args:
  description: "This job rebuilds the site map a 4 times a day"

weekly_emails:
  cron: "0 7 * * 4"
  class: WeeklyEmail
  queue: high
  args:
  description: "Send the weekly recommendation emails"