generate_sitemap:
  cron: "0 */4 * * *"
  class: RegenerateSiteMap
  queue: high
  args:
  description: "This job rebuilds the site map a 4 times a day"

google_places_update:
  cron: "0 10 * * *"
  class: GooglePlaceUpdate
  queue: high
  args:
  description: "Update n google places that haven't been updated in a month"


