development:
  adapter: mongodb
  host: localhost
  database: placeling_vanity
staging:
  adapter: mongodb
  host: ec2-184-72-38-73.us-west-1.compute.amazonaws.com
  database: placeling_vanity
production:
  adapter: mongodb
  host: ec2-107-22-193-101.compute-1.amazonaws.com
  database: placeling_vanity
