development:
  adapter: redis
  connection: redis://localhost:6379/0
staging:
  adapter: redis
  host: ec2-184-72-38-73.us-west-1.compute.amazonaws.com
production:
  adapter: redis
  host: ec2-107-22-193-101.compute-1.amazonaws.com